<?php

function log_level() {
  $severity = getenv('PENGUIN_LOG_LEVEL');

  if ($severity) {
    return defined($severity) ? constant($severity) : false;
  }

  return false;
}

function log_stdout_watchdog(array $log_entry) {
  $log_level = log_level();

  if (($log_level !== false) && ($log_level < $log_entry['severity'])) {
    return;
  } else {
    if ($log_entry['severity'] < WATCHDOG_WARNING) {
      $output = fopen('php://stderr', 'w');
    } else {
      $output = fopen('php://stdout', 'w');
    }

    $severity = strtoupper(watchdog_severity_levels()[$log_entry['severity']]);
    $user = $log_entry['user']->uid ? $log_entry['user']->name : 'anonymous';
    $request_uri = $log_entry['request_uri'];
    $referer_uri = $log_entry['referer'];
    $variables = $log_entry['variables'] ? $log_entry['variables'] : array();

    fwrite($output, t('WATCHDOG: [@severity] [@type] @message | user: @user | uri: @request_uri | referer: @referer_uri' . PHP_EOL, array(
      '@severity' => $severity,
      '@type' => $log_entry['type'],
      '@message' => strip_tags(t($log_entry['message'], $variables)),
      '@user' => $user,
      '@request_uri' => $request_uri,
      '@referer_uri' => $referer_uri,
    )));

    fclose($output);
  }
}
